config/routes.rb
Rails.application.routes.draw do
  
  get 'calls/seasons'
  get 'calls/couples'
  get 'calls/episodes'
  devise_for :users

  resources :seasons
  resources :episodes
  resources :couples
  # get 'dashboards/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dashboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/couple.rb
class Couple < ApplicationRecord
  belongs_to :season, inverse_of: :couples
end

app/models/episode.rb
class Episode < ApplicationRecord
  validates_presence_of :number, :title
  belongs_to :season, inverse_of: :episodes
  # has_many :americans, inverse_of: :episode
end

app/models/season.rb
class Season < ApplicationRecord
  # attr_accessor :id, :order
  validates_presence_of :order
  has_many :episodes, inverse_of: :season
  has_many :couples, inverse_of: :season
  # has_and_belongs_to_many :couples, class_name: 'CouplesSeasons'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,
         :confirmable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Response
  include ExceptionHandler
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  def seasons
  end

  def couples
  end

  def episodes
  end
end

app/controllers/couples_controller.rb
class CouplesController < ApplicationController
  before_action :set_couple, only: [:show, :edit, :update, :destroy]

  def index
    @couples = Couple.all
    render json: @couples
  end

  def show
    render json: @couple
  end

  # def new
  # end
  #
  # def edit
  # end
  #
  # def create
  # end
  #
  # def update
  # end
  #
  # def destroy
  # end

  private

    def set_couple
      @couple = Couple.find(params[:id])
    end

    def couple_params
      params.require(:couple).permit(:m_name, :m_city, :m_age, :w_name, :w_city,
        :w_age, season_ids: [])
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  def index
    @episodes = Episode.all
    render json: @episodes
  end

  def show
    render json: @episode
  end

  # def new
  # end
  #
  # def edit
  # end
  #
  # def create
  # end
  #
  # def update
  # end
  #
  # def destroy
  # end

  private

    def set_episode
      @episode = Episode.find(params[:id])
    end

    def episode_params
      params.require(:episode).permit(:number, :title)
    end
end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  def index
    @seasons = Season.all
    render json: @seasons
  end

  def show
    render json: @season
  end

  # def new
  # end
  #
  # def edit
  # end
  #
  # def create
  # end
  #
  # def update
  # end
  #
  # def destroy
  # end

  private

    def set_season
      @season = Season.find(params[:id])
    end

    def season_params
      params.require(:season).permit(:order)
    end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    @couples = Couple.all
    # @oldest_man = Couple.maximum('m_age')
    @oldest_man = Couple.where(m_age: Couple.maximum('m_age'))
    # @oldest_man << @oldest_man.m_name
    render json: @oldest_man
    # render partial: 'statistics/show.json'.to_json
  end
end

app/helpers/americans_helper.rb
module AmericansHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_if(view_path)
    'active' if current_page?(view_path)
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/couples_helper.rb
module CouplesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/panels_helper.rb
module PanelsHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/calls/couples.html.erb
<center>
  <h1>Get Couples</h1>
  <p>Example request: </p>
  <p>GET herokuapp.90dayapi/couples</p>
</center>
  <p>Example response:</p>

<pre>[</pre>
<pre>  {</pre>
<pre>    "id": 1,</pre>
<pre>    "m_name": "Russ",</pre>
<pre>    "m_age": 27,</pre>
<pre>    "m_city": "Owasso, OK"</pre>
<pre>    "w_name": "Paola",</pre>
<pre>    "w_age": 26,</pre>
<pre>    "w_city": "Bucaramanga, Colombia"</pre>
<pre>  },</pre>
<pre>  {...}</pre>
<pre>]</pre>

app/views/calls/episodes.html.erb
<center>
  <h1>Get Episodes</h1>
  <p>Example request: </p>
  <p>GET herokuapp.90dayapi/episodes</p>
</center>
  <p>Example response:</p>

<pre>[</pre>
<pre>  {</pre>
<pre>    "id": 1,</pre>
<pre>    "number": 1,</pre>
<pre>    "desc": "Four women come to the US..."</pre>
<pre>  },</pre>
<pre>  {...}</pre>
<pre>]</pre>

app/views/calls/seasons.html.erb
<center>
  <h1>Get Seasons</h1>
  <p>Example request: </p>
  <p>GET herokuapp.90dayapi/seasons</p>
</center>
  <p>Example response:</p>

  <pre>[</pre>
  <pre>  {</pre>
  <pre>    "id": 1,</pre>
  <pre>    "order:" 1,</pre>
  <pre>    "year": 2014,</pre>
  <pre>    "episodes": [</pre>
  <pre>       {</pre>
  <pre>         "id": 1,</pre>
  <pre>         "number": 1,</pre>
  <pre>         "title": "I Got My Visa",</pre>
  <pre>         "desc": "Four women come to the US..."</pre>
  <pre>       },</pre>
  <pre>       {...}</pre>
  <pre>    ],</pre>
  <pre>    "couples": [</pre>
  <pre>       {</pre>
  <pre>         "id": 1,</pre>
  <pre>         "m_name": "Russ",</pre>
  <pre>         "m_age": 27,</pre>
  <pre>         "m_city": "Owasso, OK"</pre>
  <pre>         "w_name": "Paola",</pre>
  <pre>         "w_age": 26,</pre>
  <pre>         "w_city": "Bucaramanga, Colombia"</pre>
  <pre>       },</pre>
  <pre>       {...}</pre>
  <pre>    ],</pre>
  <pre>  },</pre>
  <pre>  {...}</pre>
  <pre>]</pre>

app/views/dashboards/index.html.erb
<center>
  Welcome to the unofficial 90 DAY FIANCE API.
</center>

app/views/panels/index.html.erb
<h1>Panels#index</h1>
<p>Find me in app/views/panels/index.html.erb</p>

<center>
  <h3>You made it, <%= @user.email %>.</h3>
  <h3>Well done.</h3>
  <p><%= link_to 'Seasons Index', seasons_path %></p>
</center>

app/views/statistics/index.html.erb
<h1>Statistics#index</h1>
<p>Find me in app/views/statistics/index.html.erb</p>