config/routes.rb
Rails.application.routes.draw do
  
  get 'calls/seasons'
  get 'calls/couples'
  get 'calls/episodes'
  devise_for :users

  resources :seasons
  resources :episodes
  resources :couples
  # get 'dashboards/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dashboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/couple.rb
class Couple < ApplicationRecord
  belongs_to :season, inverse_of: :couples
end

app/models/episode.rb
class Episode < ApplicationRecord
  validates_presence_of :number, :title
  belongs_to :season, inverse_of: :episodes
  # has_many :americans, inverse_of: :episode
end

app/models/season.rb
class Season < ApplicationRecord
  # attr_accessor :id, :order
  validates_presence_of :order
  has_many :episodes, inverse_of: :season
  has_many :couples, inverse_of: :season
  # has_and_belongs_to_many :couples, class_name: 'CouplesSeasons'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,
         :confirmable, :lockable
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  def seasons
  end

  def couples
  end

  def episodes
  end
end

app/controllers/couples_controller.rb
class CouplesController < ApplicationController
  before_action :set_couple, only: [:show, :edit, :update, :destroy]

  def index
    @couples = Couple.all
    render json: @couples
  end

  def show
    render json: @couple
  end

  # def new
  # end
  #
  # def edit
  # end
  #
  # def create
  # end
  #
  # def update
  # end
  #
  # def destroy
  # end

  private

    def set_couple
      @couple = Couple.find(params[:id])
    end

    def couple_params
      params.require(:couple).permit(:m_name, :m_city, :m_age, :w_name, :w_city,
        :w_age, season_ids: [])
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  def index
    @episodes = Episode.all
    render json: @episodes
  end

  def show
    render json: @episode
  end

  # def new
  # end
  #
  # def edit
  # end
  #
  # def create
  # end
  #
  # def update
  # end
  #
  # def destroy
  # end

  private

    def set_episode
      @episode = Episode.find(params[:id])
    end

    def episode_params
      params.require(:episode).permit(:number, :title)
    end
end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  def index
    @seasons = Season.all
    render json: @seasons
  end

  def show
    render json: @season
  end

  # def new
  # end
  #
  # def edit
  # end
  #
  # def create
  # end
  #
  # def update
  # end
  #
  # def destroy
  # end

  private

    def set_season
      @season = Season.find(params[:id])
    end

    def season_params
      params.require(:season).permit(:order)
    end
end

app/helpers/americans_helper.rb
module AmericansHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_if(view_path)
    'active' if current_page?(view_path)
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/couples_helper.rb
module CouplesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/panels_helper.rb
module PanelsHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyDayApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'partials/header' %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class='container'>
      <div class='wrapper'>
        <%= render 'partials/side_nav' %>
        <div id='content'>
          <%= yield %>
        </div>
      </div>


    </div>

    <%= render 'partials/footer' %>

  </body>
</html>

app/views/partials/_footer.html.erb
<footer class='page-footer white' id='footer'>
  <div class='container'>
    <div class='row center'>
      <div class='col f-block'>
        <h4>CONTACT</h4>
        Want to get in touch? <br />
        I'm at <%= "#{ENV['GMAILU']}" %>.
      </div>
      <div class='col f-block'>
        <h4>MY LINKS</h4>
        <%= link_to 'github', "#{ENV['MY_GITHUB']}" %><br />
        <%= link_to 'LinkedIn', "#{ENV['MY_LI']}" %> <br />
      </div>
      <div class='col f-block'>
        <h4>ABOUT</h4>
        I built this site in Ruby on Rails <br />
        with Bootstrap for styling.
      </div>
    </div>
  </div>
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-md bg-secondary navbar-dark navbar-static-top">

  <div>
    <%= link_to "90 Day Fiance API", root_path, class: 'navbar-brand mb-0 h1' %>
  </div>

<% if user_signed_in? %>
  <ul class="navbar-nav justify-content-end ml-auto">
    <div>
      <button type="button"
              class="btn-sm navbar-toggler navbar-toggler-right"
              data-toggle="collapse"
              data-target="#myNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <li class="nav-item <%= active_if(root_path) %>">
        <%= link_to "Dashboard", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= active_if(panels_index_path) %>">
        <%= link_to "Admin Panel", panels_index_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(destroy_user_session_path) %>">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    </div>
  </ul>
<% else %>
  <ul class="navbar-nav justify-content-end ml-auto">
    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
  </ul>
<% end %>
</nav>

app/views/partials/_side_nav.erb
  <nav id='sidebar'>
    <div class="sidebar-header">
        <h3>Bootstrap Sidebar</h3>
    </div>

    <ul class="list-unstyled components">
          <p>Dummy Heading</p>
          <li class="active">
              <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
              <ul class="collapse list-unstyled" id="homeSubmenu">
                  <li>
                      <a href="#">Home 1</a>
                  </li>
                  <li>
                      <a href="#">Home 2</a>
                  </li>
                  <li>
                      <a href="#">Home 3</a>
                  </li>
              </ul>
          </li>
          <li>
            <%= link_to 'HOME', root_path %>
          </li>
          <li>
              <%= link_to 'GET seasons', calls_seasons_path %>
          </li>
          <li>
              <%= link_to 'GET episodes', calls_episodes_path %>
          </li>
          <li>
              <%= link_to 'GET couples', calls_couples_path %>
          </li>
          <li>
              <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
              <ul class="collapse list-unstyled" id="pageSubmenu">
                  <li>
                      <a href="#">Page 1</a>
                  </li>
                  <li>
                      <a href="#">Page 2</a>
                  </li>
                  <li>
                      <a href="#">Page 3</a>
                  </li>
              </ul>
          </li>
          <li>
              <a href="#">Portfolio</a>
          </li>
          <li>
              <a href="#">Contact</a>
          </li>
      </ul>
  </nav>